#!/usr/bin/env python3
"""
Streaming XML Chunk Parser with Tag Prefix Filtering

This parser processes XML chunks and emits context-aware events for each chunk:
{
    "event": "root|tag_name",  # Current context (root or tag name)
    "args": dict or None,      # Attributes for the current tag context
    "content": string          # The content/text from this chunk
}

When the context changes within a chunk, multiple events are emitted.
The parser can be configured to only recognize tags with a specific prefix.
"""

import logging
import re
from typing import TypedDict

PARAMETER_CLOSING_TAG = "</parameter>"
INVOKE_CLOSING_TAG = "</invoke>"


class LlmRecoverableErrorException(Exception):
    """Exception raised when a malformed pattern is detected in the stream but we can recover."""

    pass


class XMLChunkParserEvent(TypedDict):
    event: str
    args: dict[str, str] | None
    content: str


class XMLChunkParser:
    """
    A streaming parser that maintains context and processes XML chunks.
    """

    def __init__(self, tag_prefix: str | None = None):
        """
        Initialize the parser.

        Args:
            tag_prefix: Optional prefix for tags to recognize (e.g., "flow-").
                        If provided, only tags with this prefix will be treated as XML tags.
        """
        self.current_context = "chat"  # Start in root context
        self.current_args: dict[str, str] | None = None
        self.tag_stack: list[tuple[str, dict[str, str]]] = []  # Stack of (tag_name, args) tuples
        # TODO: Consider making this a list of known tags
        self.tag_prefix = tag_prefix

        self.pending_tag = ""  # Buffer for collecting a potential tag across chunks

        self.tag_pattern = self._build_tag_pattern()
        self._is_parameter_closing_tag_detected = False
        self._is_invoke_closing_tag_detected = False

    def _build_tag_pattern(self):
        """
        Build a regex pattern to match tags with the given prefix.
        """
        if self.tag_prefix:
            prefix_patterns = []
            for i in range(1, len(self.tag_prefix) + 1):
                prefix_patterns.append(re.escape(self.tag_prefix[:i]))
            return r"<(?=/|" + "|".join(prefix_patterns) + r")"
        return r"<(?=/|\w)"

    def process_chunk(self, chunk: str):
        """
        Process a chunk of XML-like content and return context events.
        """
        events: list[XMLChunkParserEvent] = []
        text_to_process = self.pending_tag + chunk
        self.pending_tag = ""  # Will be re-populated if text_to_process ends with a partial tag

        current_pos = 0
        while current_pos < len(text_to_process):
            # Find the next tag start
            tag_start_match = re.search(self.tag_pattern, text_to_process[current_pos:])

            if not tag_start_match:
                # No more tags in the remaining text
                content = text_to_process[current_pos:]
                if content:
                    events.append({"event": self.current_context, "args": self.current_args, "content": content})
                break  # End of processing for this chunk

            tag_start_offset = current_pos + tag_start_match.start()

            # Content before this tag
            if tag_start_offset > current_pos and not self._is_parameter_closing_tag_detected:
                content = text_to_process[current_pos:tag_start_offset]
                events.append({"event": self.current_context, "args": self.current_args, "content": content})

            # Find the tag end '>'
            tag_end_offset = text_to_process.find(">", tag_start_offset)

            if tag_end_offset == -1:
                # Incomplete tag at the end of text_to_process
                self.pending_tag = text_to_process[tag_start_offset:]
                break  # End of processing for this chunk

            # Complete tag found
            tag_str = text_to_process[tag_start_offset : tag_end_offset + 1]
            tag_processing_events = self._process_tag_string(tag_str)
            events.extend(tag_processing_events)

            current_pos = tag_end_offset + 1

        return events

    def _process_tag_string(self, tag_str: str):
        """
        Process a complete tag string and update the context if necessary.
        Returns a list of events generated by processing this tag.
        """
        generated_events: list[XMLChunkParserEvent] = []

        is_closing_tag = tag_str.startswith("</")
        is_self_closing_tag = tag_str.endswith("/>")  # Note: simplified check

        tag_name_match = None
        if is_closing_tag:
            if tag_str == PARAMETER_CLOSING_TAG:
                self._is_parameter_closing_tag_detected = True
                return generated_events
            if tag_str == INVOKE_CLOSING_TAG and self._is_parameter_closing_tag_detected:
                self._is_invoke_closing_tag_detected = True
                logging.debug("</invoke> tag detected after </parameter>")
                generated_events.append({"event": "flow-invoke-error", "args": self.current_args, "content": ""})
            tag_name_match = re.match(r"<\/([^\s>]+)", tag_str)
        else:
            tag_name_match = re.match(r"<([^\s/>]+)", tag_str)

        if not tag_name_match and not self._is_parameter_closing_tag_detected:
            # Malformed tag or not a tag structure we understand, treat as content
            generated_events.append({"event": self.current_context, "args": self.current_args, "content": tag_str})
            return generated_events

        tag_name = tag_name_match.group(1)

        # Apply prefix filter
        if self.tag_prefix and not tag_name.startswith(self.tag_prefix) and not self._is_parameter_closing_tag_detected:
            # Tag does not match prefix, treat as content
            generated_events.append({"event": self.current_context, "args": self.current_args, "content": tag_str})
            return generated_events

        # Tag matches prefix (or no prefix filter) - process it as a structural tag
        if is_closing_tag:
            if (self.tag_stack and self.tag_stack[-1][0] == tag_name) or self._is_invoke_closing_tag_detected:
                self.tag_stack.pop()
                if self.tag_stack:
                    self.current_context, self.current_args = self.tag_stack[-1]
                else:
                    self.current_context = "chat"
                    self.current_args = None
                # Emit context change event
                generated_events.append({"event": self.current_context, "args": self.current_args, "content": ""})
                self._is_parameter_closing_tag_detected = False
                self._is_invoke_closing_tag_detected = False
            else:
                # Mismatched closing tag, treat as content (or error)
                # For now, treat as content in current context
                generated_events.append({"event": self.current_context, "args": self.current_args, "content": tag_str})
        elif is_self_closing_tag:
            # Self-closing tag matching prefix - emit its "opening" then "closing" effect
            # For simplicity, we'll treat its content as empty and not change stack
            # A more complex parser might handle attributes here.
            # For this problem, a self-closing tag matching prefix effectively opens and closes.
            # We can emit its name as context, then immediately revert.
            # Or, if it doesn't change context, just acknowledge it.
            # Let's assume self-closing tags don't push to stack for this problem.
            # We'll emit an event for it, but it won't change the ongoing context.
            attrs = {}
            attr_matches = re.finditer(r'([a-zA-Z0-9_-]+)=([\'"])(.*?)\2', tag_str)
            for match in attr_matches:
                attrs[match.group(1)] = match.group(3)
            generated_events.append(
                {
                    "event": tag_name,  # Report the tag name
                    "args": attrs,
                    "content": "",  # Self-closing tags typically don't have separate content
                }
            )
            # No change to self.current_context or self.tag_stack for self-closing
        else:  # Opening tag
            attrs = {}
            attr_matches = re.finditer(r'([a-zA-Z0-9_-]+)=([\'"])(.*?)\2', tag_str)
            for match in attr_matches:
                attrs[match.group(1)] = match.group(3)

            self.tag_stack.append((tag_name, attrs))
            self.current_context = tag_name
            self.current_args = attrs
            # Emit context change event
            generated_events.append({"event": self.current_context, "args": self.current_args, "content": ""})
        return generated_events

    def reset(self):
        """Reset the parser state."""
        self.current_context = "chat"
        self.current_args = None
        self.tag_stack = []
        self.pending_tag = ""


def process_xml(xml_content: str, tag_prefix: str | None = None):
    """
    Process XML content and return a list of events.
    """
    parser = XMLChunkParser(tag_prefix=tag_prefix)
    events = parser.process_chunk(xml_content)

    last_event: XMLChunkParserEvent | None = None
    united_chunks: list[XMLChunkParserEvent] = []
    for event in events:
        if last_event and last_event["event"] == event["event"] and event["args"] == last_event["args"]:
            united_chunks[-1]["content"] += event["content"]
        else:
            united_chunks.append(event)
        last_event = event
    return united_chunks
