"""The generated per-process OpenCode hook plugin.

OpenCode is the only harness whose hook artifact is **executable code** rather
than a declarative manifest. claude/copilot get a ``hooks.json`` inside a plugin
directory named on argv; codex gets ``-c hooks.<Event>=`` overrides. OpenCode has
no plugin CLI flag at all — the plugin reaches the worker through the generated
``opencode.json`` (``plugin: ["file://…"]``), which is pointed at by
``OPENCODE_CONFIG``. See :mod:`.config_gen`, which owns that file.

So the shell-out lives inside code WE emit. Two consequences drive this module:

* the process id and the ``flow`` argv are baked in at projection time, exactly
  like the ``--process-id`` argument the other drivers put in their manifests;
* the plugin subscribes to NAMED hooks wherever one exists, and filters the
  ``event`` firehose down to a single type otherwise. The firehose is loud — a
  trivial turn emits dozens of ``plugin.added``/catalog events — and shelling out
  per event would spawn a ``flow`` process for each one.
"""

from __future__ import annotations

import json
from pathlib import Path

from flow_sdk.builtin.hooks.types import HookEventType

#: Where the generated plugin lives inside the process assets dir. Mirrors
#: ``SKILLS_SUBDIR`` so a human reading the process folder sees a shape opencode
#: itself would recognise.
PLUGIN_SUBDIR = Path(".opencode") / "plugin"
PLUGIN_FILENAME = "flowpad-hooks.js"

#: Canonical event -> the named plugin hook that carries it. Anything not here
#: is delivered through the ``event`` firehose and must be filtered by type.
NAMED_HOOKS: dict[HookEventType, str] = {
    HookEventType.USER_PROMPT_SUBMIT: "chat.message",
}

#: Canonical event -> the bus event type to filter the firehose for.
BUS_EVENTS: dict[HookEventType, str] = {
    HookEventType.SESSION_START: "session.created",
}


def plugin_path(assets_dir: Path) -> Path:
    """Where this process's generated plugin lives."""
    return Path(assets_dir) / PLUGIN_SUBDIR / PLUGIN_FILENAME


def render_plugin(*, process_id: str, flow_argv: list[str], events: tuple[HookEventType, ...]) -> str:
    """Render the plugin source. Pure, so it can be asserted on byte-for-byte.

    ``flow_argv`` is the full executable + prefix args from
    ``get_installed_flow_invocation`` — the non-writing seam, so projecting a
    hook never materializes a global runner wrapper.
    """
    named = {NAMED_HOOKS[e]: e.value for e in events if e in NAMED_HOOKS}
    bus = {BUS_EVENTS[e]: e.value for e in events if e in BUS_EVENTS}

    return f"""\
// Generated by Flowpad — do not edit. Regenerated on every launch from the
// process's configured hook events; delete the file to remove all hooks.
const PROCESS_ID = {json.dumps(process_id)};
const FLOW_ARGV = {json.dumps(flow_argv)};
const NAMED = {json.dumps(named, indent=2, sort_keys=True)};
const BUS = {json.dumps(bus, indent=2, sort_keys=True)};

export const FlowpadHooks = async ({{ $ }}) => {{
  // One report = one `flow hooks report` invocation, the same handler every
  // other harness runs. Failures are swallowed: a hook must never break a turn.
  const report = async (eventName, payload) => {{
    const body = JSON.stringify({{ hook_event_name: eventName, ...payload }});
    try {{
      // `flow hooks report` reads its payload from stdin, and opencode's `$`
      // has NO .stdin() method (verified: it is undefined) — a pipeline is the
      // only way to feed it. Interpolated values are escaped by the shell, so
      // the JSON arrives intact.
      await $`echo ${{body}} | ${{FLOW_ARGV}} hooks report --process-id ${{PROCESS_ID}}`;
    }} catch (err) {{
      console.error(`[flowpad] hook report failed for ${{eventName}}:`, err);
    }}
  }};

  const hooks = {{}};

  for (const [hookName, eventName] of Object.entries(NAMED)) {{
    hooks[hookName] = async (input) => {{
      await report(eventName, {{ cwd: process.cwd(), raw: input ?? null }});
    }};
  }}

  if (Object.keys(BUS).length > 0) {{
    // The firehose carries dozens of events per turn; only the mapped types
    // reach the CLI.
    hooks.event = async ({{ event }}) => {{
      const eventName = BUS[event?.type];
      if (!eventName) return;
      await report(eventName, {{ cwd: process.cwd(), raw: event ?? null }});
    }};
  }}

  return hooks;
}};
"""
