"""Renders ``.env.<name>.local`` — the file both vite and the backend read.

It lives at the **repo root**, not in ``ui/``: vite's ``envDir`` is
``path.resolve(__dirname, '..')`` (``ui/vite.config.ts``), so the repo root is
the only directory it loads env from even though the dev server runs from
``ui/``. Precedence is ``.env`` → ``.env.local`` → ``.env.<mode>`` →
``.env.<mode>.local``, and the launcher passes ``--mode <name>``, which is what
lets a per-instance file out-precede a developer's ``.env.local``.

The shape differs by kind, and the hub-ui difference is load-bearing rather than
cosmetic. ``ui/tests/hub/_instances.ts`` gates desk-instance tests on a numeric
``LOCAL_SERVER_PORT`` and a ``VITE_API_URL`` pointing at that port; a hub-ui
instance omits the former entirely, so those gates reject it **structurally**.
That is the intended behavior — a hub-ui instance is not a desk instance and
must never be silently bound as one.
"""

from __future__ import annotations

import os

from . import paths
from .model import InstanceKind, LauncherRecord, Role

DEFAULT_HUB_URL = "http://localhost:8093"


def default_email(name: str) -> str:
    """``<name>@local.test`` — a contract: ``tests/hub_tests/*`` derive it."""
    return f"{name}@local.test"


def default_password(name: str) -> str:
    """``<name>-pw-1234`` — a contract: hard-coded as ``f"{BOB_INSTANCE}-pw-1234"``."""
    return f"{name}-pw-1234"


def default_hub_url() -> str:
    return os.environ.get("FLOWPAD_HUB_URL") or DEFAULT_HUB_URL


def render(rec: LauncherRecord, *, password: str) -> str:
    """The full text of ``.env.<name>.local`` for this record."""
    lines = [
        f"# Auto-generated by flow instance ctl for instance '{rec.name}' (kind={rec.kind}). Safe to delete.",
        f"FLOW_INSTANCE={rec.name}",
        f"FLOWPAD_HUB_URL={rec.hub_url}",
        f"FLOWPAD_CLOUD_USER_EMAIL={rec.email}",
        f"FLOWPAD_CLOUD_USER_PASSWORD={password}",
    ]

    if Role.FRONTEND in rec.roles and rec.frontend.port:
        lines.append(f"VITE_PORT={rec.frontend.port}")

    if rec.kind is InstanceKind.HUB_UI:
        # No LOCAL_SERVER_PORT: there is no local backend, and its absence is
        # what makes the desk-instance harness gates reject this instance.
        # VITE_FORCE_HUB overwrites bootstrapInfo.supported_pages with ['hub']
        # in ts_sdk/src/main.ts, which is required while a *local* backend would
        # answer ["desk","hub"]; a real hub returning ["hub"] makes it a no-op.
        lines.append(f"VITE_API_URL={rec.hub_url}")
        lines.append("VITE_FORCE_HUB=true")
    else:
        if rec.backend.port:
            lines.append(f"LOCAL_SERVER_PORT={rec.backend.port}")
            if Role.FRONTEND in rec.roles:
                lines.append(f"VITE_API_URL=http://localhost:{rec.backend.port}")
        # MINIHUB_RELOAD=False keeps the backend single-process, so a PID kill
        # is sufficient. FLOWPAD_SKIP_DOTENV stops run.py's
        # load_dotenv(override=True) on .env.local from clobbering the ports we
        # just injected — both are load-bearing, not tuning.
        lines.append("MINIHUB_RELOAD=False")
        lines.append("FLOWPAD_SKIP_DOTENV=true")
        # The isolated backend skips the repo dotenv, so an explicitly exported
        # E2B credential has to be carried across that boundary or a
        # provider-backed QA instance silently loses sandbox capability.
        e2b = os.environ.get("E2B_KEY")
        if e2b:
            lines.append(f"E2B_KEY={e2b}")

    return "\n".join(lines) + "\n"


def write_env_file(rec: LauncherRecord, *, password: str) -> None:
    paths.env_file(rec.name).write_text(render(rec, password=password))


def read_env_file(name: str) -> dict[str, str]:
    """Parse ``.env.<name>.local`` without mutating ``os.environ``."""
    from dotenv import dotenv_values

    path = paths.env_file(name)
    if not path.exists():
        return {}
    return {k: v for k, v in dotenv_values(path).items() if v is not None}


def build_named_instance_env(settings, *, generation: str | None = None) -> dict[str, str]:
    """The standard backend environment, pinned to one resolved instance."""
    env = os.environ.copy()
    env.update(read_env_file(settings.instance_name))
    env.update(
        {
            "FLOW_INSTANCE": settings.instance_name,
            "FLOW_HOME": str(settings.flow_home),
            "LOCAL_SERVER_PORT": str(settings.port),
            "FLOWPAD_SKIP_DOTENV": "true",
            "MINIHUB_RELOAD": "False",
        }
    )
    if generation:
        env["FLOWPAD_SERVICE_GENERATION"] = generation
    return env


def delete_env_file(name: str) -> bool:
    path = paths.env_file(name)
    existed = path.exists()
    path.unlink(missing_ok=True)
    return existed
