"""Tests for Claude Code settings.json FsRecords (Phase 1 + Phase 2 + Phase 3 + Phase 4)."""

import json
import uuid as _uuid

import pytest

# Stable UUID5 IDs for singleton settings records
_SETTINGS_ID = str(_uuid.uuid5(_uuid.NAMESPACE_DNS, "claude_settings_json:default"))
_PERMISSIONS_ID = str(_uuid.uuid5(_uuid.NAMESPACE_DNS, "claude_settings_json_permissions:default"))
_SANDBOX_ID = str(_uuid.uuid5(_uuid.NAMESPACE_DNS, "claude_settings_json_sandbox:default"))
_ATTRIBUTION_ID = str(_uuid.uuid5(_uuid.NAMESPACE_DNS, "claude_settings_json_attribution:default"))

from flow_sdk.fs_store import RecordType
from flow_sdk.fs_records.claude.claude_settings_json import (
    ClaudeSettingsJsonRecordList,
    ClaudeSettingsJsonFsRecord,
    ClaudePermissionsFsRecord,
    ClaudeSandboxFsRecord,
    ClaudeAttributionFsRecord,
)
from flow_sdk.fs_records.claude.claude_managed_settings import (
    ClaudeManagedSettingsFsRecord,
    ClaudeManagedSettingsRecordList,
)
from flow_sdk.fs_records.claude.claude_mcp_server import ClaudeMcpServerFsRecord
from flow_sdk.fs_records.claude.claude_mcp_json import ClaudeMcpJsonRecordList


# ---------------------------------------------------------------------------
# Sample data fixtures
# ---------------------------------------------------------------------------

SAMPLE_SETTINGS_JSON = {
    "model": "claude-sonnet-4-6",
    "availableModels": ["claude-sonnet-4-6", "claude-opus-4-6"],
    "alwaysThinkingEnabled": True,
    "apiKeyHelper": "/usr/local/bin/get-api-key",
    "forceLoginMethod": "console",
    "forceLoginOrgUUID": "org-abc-123",
    "enableAllProjectMcpServers": True,
    "enabledMcpjsonServers": ["server-a", "server-b"],
    "disabledMcpjsonServers": ["server-c"],
    "hooks": {
        "PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": "echo pre"}]}],
    },
    "disableAllHooks": False,
    "outputStyle": "concise",
    "language": "en",
    "showTurnDuration": True,
    "spinnerVerbs": {"mode": "custom", "verbs": ["thinking", "pondering"]},
    "spinnerTipsEnabled": True,
    "spinnerTipsOverride": {"excludeDefault": True, "tips": ["Use /help"]},
    "terminalProgressBarEnabled": True,
    "prefersReducedMotion": False,
    "fileSuggestion": {"include": ["src/**"]},
    "respectGitignore": True,
    "plansDirectory": "/tmp/plans",
    "env": {"MY_VAR": "value"},
    "autoUpdatesChannel": "stable",
    "cleanupPeriodDays": 30,
    "statusLine": {"enabled": True},
    "enabledPlugins": {"my-plugin": True},
    "extraKnownMarketplaces": {"custom": {"url": "https://example.com"}},
    "awsAuthRefresh": "/usr/local/bin/aws-refresh",
    "awsCredentialExport": "/usr/local/bin/aws-export",
    "otelHeadersHelper": "/usr/local/bin/otel-helper",
    "teammateMode": "full",
    "companyAnnouncements": ["Welcome to the team!"],
    "includeCoAuthoredBy": False,
    "permissions": {
        "allow": ["Read", "Glob", "Grep"],
        "ask": ["Bash", "Edit", "Write"],
        "deny": ["mcp__dangerous__tool"],
        "additionalDirectories": ["/tmp/extra"],
        "defaultMode": "acceptEdits",
        "disableBypassPermissionsMode": "true",
    },
    "sandbox": {
        "enabled": True,
        "autoAllowBashIfSandboxed": True,
        "excludedCommands": ["rm -rf /"],
        "allowUnsandboxedCommands": False,
        "enableWeakerNestedSandbox": False,
        "network": {
            "allowedDomains": ["api.example.com", "cdn.example.com"],
            "allowUnixSockets": ["/tmp/my.sock"],
            "allowAllUnixSockets": False,
            "allowLocalBinding": True,
            "httpProxyPort": 8080,
            "socksProxyPort": 1080,
        },
    },
    "attribution": {
        "commit": "Generated by Claude Code",
        "pr": "AI-assisted PR",
    },
}

SAMPLE_MANAGED_SETTINGS = {
    "allowedMcpServers": [{"name": "approved-server", "url": "https://approved.example.com"}],
    "deniedMcpServers": [{"name": "blocked-server"}],
    "allowManagedMcpServersOnly": True,
    "allowManagedHooksOnly": True,
    "allowManagedPermissionRulesOnly": False,
    "strictKnownMarketplaces": [{"name": "internal", "url": "https://internal.example.com"}],
    "blockedMarketplaces": [{"name": "untrusted"}],
    "sandbox": {
        "network": {
            "allowManagedDomainsOnly": True,
        },
    },
}

SAMPLE_MCP_JSON = {
    "mcpServers": {
        "filesystem": {
            "type": "stdio",
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"],
            "env": {"DEBUG": "true"},
        },
        "remote-api": {
            "type": "sse",
            "url": "https://mcp.example.com/sse",
        },
        "http-server": {
            "type": "http",
            "url": "https://mcp.example.com/http",
            "env": {"API_KEY": "secret"},
        },
    },
}


# ---------------------------------------------------------------------------
# Phase 1: settings.json records
# ---------------------------------------------------------------------------


class TestSettingsJsonRecordList:
    def test_parse_full_settings(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        records = list(rl)

        # Root + permissions + sandbox + attribution = 4 records
        assert len(records) == 4

    def test_root_record_fields(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        root = rl.root

        assert isinstance(root, ClaudeSettingsJsonFsRecord)
        assert root.type == RecordType.CLAUDE_SETTINGS_JSON
        assert root.model == "claude-sonnet-4-6"
        assert root.available_models == ["claude-sonnet-4-6", "claude-opus-4-6"]
        assert root.always_thinking_enabled is True
        assert root.api_key_helper == "/usr/local/bin/get-api-key"
        assert root.force_login_method == "console"
        assert root.force_login_org_uuid == "org-abc-123"
        assert root.enable_all_project_mcp_servers is True
        assert root.enabled_mcpjson_servers == ["server-a", "server-b"]
        assert root.disabled_mcpjson_servers == ["server-c"]
        assert "PreToolUse" in root.hooks
        assert root.disable_all_hooks is False
        assert root.output_style == "concise"
        assert root.language == "en"
        assert root.show_turn_duration is True
        assert root.spinner_tips_enabled is True
        assert root.terminal_progress_bar_enabled is True
        assert root.prefers_reduced_motion is False
        assert root.respect_gitignore is True
        assert root.plans_directory == "/tmp/plans"
        assert root.env == {"MY_VAR": "value"}
        assert root.auto_updates_channel == "stable"
        assert root.cleanup_period_days == 30
        assert root.enabled_plugins == {"my-plugin": True}
        assert root.aws_auth_refresh == "/usr/local/bin/aws-refresh"
        assert root.otel_headers_helper == "/usr/local/bin/otel-helper"
        assert root.teammate_mode == "full"
        assert root.company_announcements == ["Welcome to the team!"]
        assert root.include_co_authored_by is False

    def test_permissions_record(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        perms = rl.permissions

        assert perms is not None
        assert isinstance(perms, ClaudePermissionsFsRecord)
        assert perms.type == RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS
        assert perms.json_path == "/permissions"
        assert perms.allow == ["Read", "Glob", "Grep"]
        assert perms.ask == ["Bash", "Edit", "Write"]
        assert perms.deny == ["mcp__dangerous__tool"]
        assert perms.additional_directories == ["/tmp/extra"]
        assert perms.default_mode == "acceptEdits"
        assert perms.disable_bypass_permissions_mode == "true"
        assert perms.parent_ref is not None

    def test_sandbox_record(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        sandbox = rl.sandbox

        assert sandbox is not None
        assert isinstance(sandbox, ClaudeSandboxFsRecord)
        assert sandbox.type == RecordType.CLAUDE_SETTINGS_JSON_SANDBOX
        assert sandbox.json_path == "/sandbox"
        assert sandbox.enabled is True
        assert sandbox.auto_allow_bash_if_sandboxed is True
        assert sandbox.excluded_commands == ["rm -rf /"]
        assert sandbox.allow_unsandboxed_commands is False
        assert sandbox.enable_weaker_nested_sandbox is False
        assert sandbox.network_allowed_domains == ["api.example.com", "cdn.example.com"]
        assert sandbox.network_allow_unix_sockets == ["/tmp/my.sock"]
        assert sandbox.network_allow_all_unix_sockets is False
        assert sandbox.network_allow_local_binding is True
        assert sandbox.network_http_proxy_port == 8080
        assert sandbox.network_socks_proxy_port == 1080

    def test_attribution_record(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        attr = rl.attribution

        assert attr is not None
        assert isinstance(attr, ClaudeAttributionFsRecord)
        assert attr.type == RecordType.CLAUDE_SETTINGS_JSON_ATTRIBUTION
        assert attr.json_path == "/attribution"
        assert attr.commit == "Generated by Claude Code"
        assert attr.pr == "AI-assisted PR"

    def test_empty_file(self, tmp_path):
        """Empty {} file produces no records (base class treats {} as empty)."""
        f = tmp_path / "settings.json"
        f.write_text("{}")

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        records = list(rl)
        assert len(records) == 0

    def test_minimal_file(self, tmp_path):
        """A file with at least one key produces a root record."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({"model": ""}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        records = list(rl)

        assert len(records) == 1
        root = rl.root
        assert root.model == ""
        assert rl.permissions is None
        assert rl.sandbox is None
        assert rl.attribution is None

    def test_missing_file(self, tmp_path):
        f = tmp_path / "nonexistent.json"
        rl = ClaudeSettingsJsonRecordList(source_file=f)
        records = list(rl)
        assert len(records) == 0

    def test_partial_settings(self, tmp_path):
        """Only model and permissions, no sandbox or attribution."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "model": "claude-haiku-4-5-20251001",
            "permissions": {"allow": ["Read"]},
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        records = list(rl)

        assert len(records) == 2  # root + permissions
        assert rl.root.model == "claude-haiku-4-5-20251001"
        assert rl.permissions is not None
        assert rl.permissions.allow == ["Read"]
        assert rl.sandbox is None
        assert rl.attribution is None

    def test_writable_records(self, tmp_path):
        """Verify settings.json records are writable (not read-only)."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        root = rl.root
        perms = rl.permissions

        # These should not be read-only (no FSRef sentinel set)
        assert root._is_read_only() is False
        assert perms._is_read_only() is False

    def test_by_type(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps(SAMPLE_SETTINGS_JSON))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        perms_list = rl.by_type(RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS)
        assert len(perms_list) == 1

    def test_reload(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({"model": "v1"}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        assert rl.root.model == "v1"

        f.write_text(json.dumps({"model": "v2"}))
        rl.reload()
        assert rl.root.model == "v2"


# ---------------------------------------------------------------------------
# Phase 2: ClaudeMcpServerFsRecord missing fields
# ---------------------------------------------------------------------------


class TestMcpServerMissingFields:
    def test_url_field_exists(self):
        srv = ClaudeMcpServerFsRecord(
            server_name="remote",
            server_type="sse",
            url="https://mcp.example.com/sse",
        )
        assert srv.url == "https://mcp.example.com/sse"
        assert srv.server_type == "sse"

    def test_server_type_field(self):
        srv = ClaudeMcpServerFsRecord(
            server_name="local",
            server_type="stdio",
            command="npx",
            args=["-y", "server"],
        )
        assert srv.server_type == "stdio"
        assert srv.command == "npx"

    def test_backward_compatible_defaults(self):
        """Existing code that doesn't pass url/server_type should still work."""
        srv = ClaudeMcpServerFsRecord(server_name="old-style", command="my-cmd")
        assert srv.url == ""
        assert srv.server_type == ""
        assert srv.command == "my-cmd"

    def test_http_transport(self):
        srv = ClaudeMcpServerFsRecord(
            server_name="http-srv",
            server_type="http",
            url="https://mcp.example.com/http",
        )
        assert srv.server_type == "http"
        assert srv.url == "https://mcp.example.com/http"
        assert srv.command == ""


# ---------------------------------------------------------------------------
# Phase 3: managed-settings.json
# ---------------------------------------------------------------------------


class TestManagedSettingsRecord:
    def test_parse_managed_settings(self, tmp_path):
        f = tmp_path / "managed-settings.json"
        f.write_text(json.dumps(SAMPLE_MANAGED_SETTINGS))

        rl = ClaudeManagedSettingsRecordList(source_file=f)
        root = rl.root

        assert isinstance(root, ClaudeManagedSettingsFsRecord)
        assert root.type == RecordType.CLAUDE_MANAGED_SETTINGS
        assert root.allow_managed_mcp_servers_only is True
        assert root.allow_managed_hooks_only is True
        assert root.allow_managed_permission_rules_only is False
        assert len(root.allowed_mcp_servers) == 1
        assert root.allowed_mcp_servers[0]["name"] == "approved-server"
        assert len(root.denied_mcp_servers) == 1
        assert len(root.strict_known_marketplaces) == 1
        assert len(root.blocked_marketplaces) == 1
        assert root.sandbox_network_allow_managed_domains_only is True

    def test_read_only(self, tmp_path):
        f = tmp_path / "managed-settings.json"
        f.write_text(json.dumps(SAMPLE_MANAGED_SETTINGS))

        rl = ClaudeManagedSettingsRecordList(source_file=f)
        assert rl.root._is_read_only() is True

    def test_empty_managed_settings(self, tmp_path):
        """Empty {} file produces no records (base class treats {} as empty)."""
        f = tmp_path / "managed-settings.json"
        f.write_text("{}")

        rl = ClaudeManagedSettingsRecordList(source_file=f)
        assert len(list(rl)) == 0

    def test_minimal_managed_settings(self, tmp_path):
        """A file with at least one key produces a root record with defaults."""
        f = tmp_path / "managed-settings.json"
        f.write_text(json.dumps({"allowManagedMcpServersOnly": False}))

        rl = ClaudeManagedSettingsRecordList(source_file=f)
        root = rl.root
        assert root.allow_managed_mcp_servers_only is False
        assert root.allowed_mcp_servers == []

    def test_missing_file(self, tmp_path):
        f = tmp_path / "nonexistent.json"
        rl = ClaudeManagedSettingsRecordList(source_file=f)
        assert len(list(rl)) == 0


# ---------------------------------------------------------------------------
# Phase 4: .mcp.json JsonFileRecordStore
# ---------------------------------------------------------------------------


class TestMcpJsonRecordList:
    def test_parse_mcp_json(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f, scope="project")
        servers = rl.servers

        assert len(servers) == 3

    def test_stdio_server(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f, scope="project")
        srv = rl.get_server("filesystem")

        assert srv is not None
        assert srv.server_name == "filesystem"
        assert srv.server_type == "stdio"
        assert srv.command == "npx"
        assert srv.args == ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
        assert srv.env == {"DEBUG": "true"}
        assert srv.url == ""
        assert srv.scope == "project"
        assert srv.json_path == "/mcpServers/filesystem"

    def test_sse_server(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f, scope="user")
        srv = rl.get_server("remote-api")

        assert srv is not None
        assert srv.server_type == "sse"
        assert srv.url == "https://mcp.example.com/sse"
        assert srv.command == ""
        assert srv.scope == "user"

    def test_http_server(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f)
        srv = rl.get_server("http-server")

        assert srv is not None
        assert srv.server_type == "http"
        assert srv.url == "https://mcp.example.com/http"
        assert srv.env == {"API_KEY": "secret"}

    def test_json_path_escaping(self, tmp_path):
        """Server names with special characters should be escaped in json_path."""
        data = {"mcpServers": {"my/server~name": {"type": "stdio", "command": "test"}}}
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(data))

        rl = ClaudeMcpJsonRecordList(source_file=f)
        srv = rl.get_server("my/server~name")

        assert srv is not None
        assert srv.json_path == "/mcpServers/my~1server~0name"

    def test_empty_mcp_json(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text("{}")

        rl = ClaudeMcpJsonRecordList(source_file=f)
        assert len(rl.servers) == 0

    def test_missing_file(self, tmp_path):
        f = tmp_path / "nonexistent.json"
        rl = ClaudeMcpJsonRecordList(source_file=f)
        assert len(list(rl)) == 0

    def test_source_file_set_on_records(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f)
        for srv in rl:
            assert srv.source_file == str(f)

    def test_server_id_includes_scope(self, tmp_path):
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(SAMPLE_MCP_JSON))

        rl = ClaudeMcpJsonRecordList(source_file=f, scope="project")
        srv = rl.get_server("filesystem")
        assert srv.id == "project:filesystem"

    def test_invalid_server_data_skipped(self, tmp_path):
        """Non-dict server entries should be silently skipped."""
        data = {"mcpServers": {"good": {"type": "stdio", "command": "ok"}, "bad": "not-a-dict"}}
        f = tmp_path / ".mcp.json"
        f.write_text(json.dumps(data))

        rl = ClaudeMcpJsonRecordList(source_file=f)
        assert len(rl.servers) == 1
        assert rl.servers[0].server_name == "good"


# ---------------------------------------------------------------------------
# Import tests
# ---------------------------------------------------------------------------


class TestImports:
    def test_import_from_claude_init(self):
        """All new types should be importable from the claude package."""
        from flow_sdk.fs_records.claude import (
            ClaudeSettingsJsonRecordList,
            ClaudeSettingsJsonFsRecord,
            ClaudePermissionsFsRecord,
            ClaudeSandboxFsRecord,
            ClaudeAttributionFsRecord,
            ClaudeManagedSettingsFsRecord,
            ClaudeManagedSettingsRecordList,
            ClaudeMcpJsonRecordList,
        )

    def test_record_types_exist(self):
        """All new RecordType constants should exist."""
        assert RecordType.CLAUDE_SETTINGS_JSON == "claude_settings_json"
        assert RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS == "claude_settings_json:permissions"
        assert RecordType.CLAUDE_SETTINGS_JSON_SANDBOX == "claude_settings_json:sandbox"
        assert RecordType.CLAUDE_SETTINGS_JSON_ATTRIBUTION == "claude_settings_json:attribution"
        assert RecordType.CLAUDE_MANAGED_SETTINGS == "claude_managed_settings"
        assert RecordType.CLAUDE_MCP_JSON == "claude_mcp_json"


# ---------------------------------------------------------------------------
# Write-back tests (JsonFileRecordStore CRUD)
# ---------------------------------------------------------------------------


class TestWriteBack:
    def test_update_root_env_var(self, tmp_path):
        """Update env vars on root record and verify source file changes."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({"model": "claude-sonnet-4-6", "env": {"OLD": "val"}}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rec = rl.update(
            RecordType.CLAUDE_SETTINGS_JSON, _SETTINGS_ID,
            {"env": {"OLD": "val", "NEW": "hello"}},
        )

        assert rec.env == {"OLD": "val", "NEW": "hello"}

        # Verify the source file was updated
        raw = json.loads(f.read_text())
        assert raw["env"] == {"OLD": "val", "NEW": "hello"}
        # model should still be there
        assert raw["model"] == "claude-sonnet-4-6"

    def test_update_permissions(self, tmp_path):
        """Update permissions sub-record and verify source file changes."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "model": "test",
            "permissions": {"allow": ["Read"], "deny": []},
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rec = rl.update(
            RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS, _PERMISSIONS_ID,
            {"allow": ["Read", "Bash", "Edit"]},
        )

        assert rec.allow == ["Read", "Bash", "Edit"]

        # Verify source file
        raw = json.loads(f.read_text())
        assert raw["permissions"]["allow"] == ["Read", "Bash", "Edit"]
        # Root-level model untouched
        assert raw["model"] == "test"

    def test_update_sandbox_with_network(self, tmp_path):
        """Update sandbox (which has nested network block) and verify roundtrip."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "sandbox": {
                "enabled": False,
                "network": {"allowedDomains": ["old.com"]},
            },
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rec = rl.update(
            RecordType.CLAUDE_SETTINGS_JSON_SANDBOX, _SANDBOX_ID,
            {"enabled": True, "network_allowed_domains": ["new.com", "api.com"]},
        )

        assert rec.enabled is True
        assert rec.network_allowed_domains == ["new.com", "api.com"]

        # Verify source file has proper nested structure
        raw = json.loads(f.read_text())
        assert raw["sandbox"]["enabled"] is True
        assert raw["sandbox"]["network"]["allowedDomains"] == ["new.com", "api.com"]

    def test_update_attribution(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "attribution": {"commit": "old", "pr": "old"},
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rec = rl.update(
            RecordType.CLAUDE_SETTINGS_JSON_ATTRIBUTION, _ATTRIBUTION_ID,
            {"commit": "Generated by Claude", "pr": "AI-assisted"},
        )

        raw = json.loads(f.read_text())
        assert raw["attribution"]["commit"] == "Generated by Claude"
        assert raw["attribution"]["pr"] == "AI-assisted"

    def test_delete_sub_record(self, tmp_path):
        """Delete a sub-record (e.g. permissions) from the source file."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "model": "test",
            "permissions": {"allow": ["Read"]},
            "sandbox": {"enabled": True},
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        deleted = rl.delete_record(RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS, _PERMISSIONS_ID)

        assert deleted is True

        raw = json.loads(f.read_text())
        assert "permissions" not in raw
        assert raw["model"] == "test"
        assert raw["sandbox"]["enabled"] is True

    def test_delete_nonexistent_returns_false(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({"model": "test"}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        deleted = rl.delete_record(RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS, _PERMISSIONS_ID)
        assert deleted is False

    def test_update_nonexistent_raises(self, tmp_path):
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({"model": "test"}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        with pytest.raises(KeyError):
            rl.update(RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS, _PERMISSIONS_ID, {"allow": []})

    def test_update_creates_source_file(self, tmp_path):
        """Update on a non-existent file should create it."""
        f = tmp_path / "settings.json"
        # File doesn't exist yet — write minimal data to create root record
        f.write_text(json.dumps({"model": "initial"}))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rl.update(RecordType.CLAUDE_SETTINGS_JSON, _SETTINGS_ID, {"language": "fr"})

        raw = json.loads(f.read_text())
        assert raw["language"] == "fr"
        assert raw["model"] == "initial"

    def test_write_preserves_unknown_keys(self, tmp_path):
        """Keys in the source file not captured by any record should survive."""
        f = tmp_path / "settings.json"
        f.write_text(json.dumps({
            "model": "test",
            "someFutureKey": "preserve-me",
            "permissions": {"allow": ["Read"]},
        }))

        rl = ClaudeSettingsJsonRecordList(source_file=f)
        rl.update(
            RecordType.CLAUDE_SETTINGS_JSON_PERMISSIONS, _PERMISSIONS_ID,
            {"allow": ["Read", "Bash"]},
        )

        raw = json.loads(f.read_text())
        assert raw["someFutureKey"] == "preserve-me"
        assert raw["permissions"]["allow"] == ["Read", "Bash"]


# ---------------------------------------------------------------------------
# File pattern registry tests
# ---------------------------------------------------------------------------


class TestFilePatternRegistry:
    def test_settings_json_pattern_registered(self):
        from flow_sdk.fs_store.source_file_registry import resolve_list_class

        assert resolve_list_class("settings.json") is ClaudeSettingsJsonRecordList
        assert resolve_list_class("settings.local.json") is ClaudeSettingsJsonRecordList

    def test_types_in_type_registry(self):
        from flow_sdk.fs_store.factory.type_registry import type_registry

        assert type_registry.get(RecordType.CLAUDE_SETTINGS_JSON) is ClaudeSettingsJsonFsRecord
