import { Artifact, CodebaseReferenceType, Flow, FlowData, FlowElementTypes } from '@sdk';
import { useCallback, useMemo } from 'react';
import { useProcessStream } from './useProcessStream';

/**
 * Hook to extract streaming artifacts from Flow entity's FlowData stream
 *
 * Parses 'result' FlowData tags and creates Artifact objects from the active flow stream
 * Used for displaying file results generated by agent during execution
 *
 * @param flow - Flow entity (or null)
 * @returns Object with artifacts array, artifact paths, and getStreamingFlowDataAfter callback
 */
export function useProcessStreamingArtifacts(flow: Flow | null | undefined): {
  artifacts: Artifact[];
  artifactPaths: string[];
  getStreamingFlowDataAfter: (timestamp: number) => FlowData<Artifact>[];
} {
  const { data: flowData } = useProcessStream(flow ?? null);

  const artifactsData = useMemo(() => {
    if (!flowData || flowData.length === 0) {
      return { artifacts: [], artifactPaths: [] };
    }

    const artifacts: Artifact[] = [];
    const artifactPaths: string[] = [];

    // Process all 'result' FlowData tags
    for (const fd of flowData) {
      if (fd.elementType === FlowElementTypes.RESULT) {
        // Check if data is already an Artifact instance (from data-type="entity")
        if (fd.data instanceof Artifact) {
          const artifactPath = fd.data.path;
          if (artifactPath) {
            artifactPaths.push(artifactPath);
            artifacts.push(fd.data);
          }
        }
        // Check if data has artifact type with path (from data-type="object")
        else if (fd.data && typeof fd.data === 'object' && fd.data.type === Artifact.type) {
          const artifactData = fd.data as Artifact;
          const artifactPath = artifactData.path;
          if (artifactPath) {
            const artifact = new Artifact({
              id: artifactData.id,
              name: artifactData.name || artifactPath.split('/').pop() || artifactPath,
              path: artifactPath,
              ref_type: artifactData.ref_type || CodebaseReferenceType.FILE,
              description: artifactData.description,
              metadata: artifactData.metadata,
            });
            artifactPaths.push(artifactPath);
            artifacts.push(artifact);
          }
        }
      }
    }

    return { artifacts, artifactPaths };
  }, [flowData]);

  const getStreamingFlowDataAfter = useCallback(
    (timestamp: number): FlowData<Artifact>[] => {
      if (!flowData || flowData.length === 0) {
        return [];
      }

      const result: FlowData<Artifact>[] = [];

      for (const fd of flowData) {
        // Check both Artifact instances and plain objects with artifact type (during streaming)
        // Capture the data property at this moment to avoid issues if it changes mid-iteration
        const hasArtifactData =
          fd.data && (fd.data instanceof Artifact || (typeof fd.data === 'object' && fd.data.type === Artifact.type));
        if (fd.elementType !== FlowElementTypes.RESULT || !hasArtifactData) {
          continue;
        }
        // Parse timestamp - handle both string (ISO format) and number types
        // Convert ISO string to milliseconds, or use number directly if already in milliseconds
        const fdTimestamp = typeof fd.timestamp === 'string' ? new Date(fd.timestamp).getTime() : fd.timestamp;

        // Only include FlowData after the specified timestamp
        if (fdTimestamp > timestamp) {
          result.push(fd as FlowData<Artifact>);
        }
      }

      return result;
    },
    [flowData],
  );

  return {
    ...artifactsData,
    getStreamingFlowDataAfter,
  };
}
