export const EntityTypes = {
  AgenticProcess: 'agentic_process',
  Agent: 'agent',
  Annotation: 'annotation',
  ApiKey: 'api_key',
  Artifact: 'artifact',
  ArtifactRelation: 'artifact_relation',
  Bookmark: 'bookmark',
  CodeRef: 'code_ref',
  Comment: 'comment',
  ComputeNode: 'compute_node',
  CronEvent: 'cron_event',
  Flow: 'flow',
  FsItem: 'fs_item',
  Func: 'func',
  GraphContext: 'graph_context',
  Job: 'job',
  JobExecution: 'job_execution',
  KnowledgeBase: 'knowledge_base',
  Mention: 'mention',
  Page: 'page',
  Plugin: 'plugin',
  PluginManifest: 'plugin_manifest',
  ProcessResult: 'process_result',
  Project: 'project',
  Question: 'question',
  Shell: 'shell',
  Skill: 'skill',
  Task: 'task',
  Trigger: 'trigger',
  User: 'user',
  Visitor: 'visitor',
  WebDomain: 'web_domain',
  Workflow: 'workflow',
  Workspace: 'workspace',
} as const;

export type EntityType = (typeof EntityTypes)[keyof typeof EntityTypes];
