/**
 * "This run's artifacts" is a QUERY over `generated_by` server-side, never a
 * list field on the process row — so two registrations landing at once cannot
 * clobber each other's append. `proc.loadArtifacts()` is the one-shot LOAD half
 * of that; the realtime half is the `artifact.*` bus lane
 * (`agentic-process-artifacts-live.test.ts`).
 *
 * This file pins the REQUEST: the action is registered on the backend as
 * `@action.get(action_name="artifacts")` — a pure read with no body, exactly
 * like its sibling `get-assets`. The method is asserted explicitly because a
 * mismatch is invisible to the type system and would surface only as a 405
 * against a live backend, long after this tier is green.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AgenticProcess, Artifact, ProcessStatus, dataManager } from '@sdk';

/** Factory so the spy's exact MockInstance type is inferred, not restated. */
const spyCallAction = () => vi.spyOn(dataManager, 'callAction');

const PROC_ID = 'e5a2c1b0-0000-4000-8000-0000000000aa';
const PROC_TYPEID = `agentic_process-${PROC_ID}`;

let seq = 0;
const row = (name: string, overrides: Record<string, unknown> = {}) => ({
  id: `9c4d0e11-0000-4000-8000-00000000${String(++seq).padStart(4, '0')}`,
  type: 'artifact',
  name,
  kind: 'content.file',
  asset_ref: `/repo/${name}`,
  generated_by: PROC_TYPEID,
  ...overrides,
});

describe('AgenticProcess.loadArtifacts', () => {
  let callActionSpy: ReturnType<typeof spyCallAction>;

  beforeEach(() => {
    callActionSpy = spyCallAction();
  });

  afterEach(() => {
    callActionSpy.mockRestore();
  });

  it('GETs the `artifacts` action scoped to this process, with no body', async () => {
    callActionSpy.mockResolvedValue({ artifacts: [] } as never);
    const proc = new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING });

    await proc.loadArtifacts();

    expect(callActionSpy).toHaveBeenCalledOnce();
    const actionInfo = callActionSpy.mock.calls[0][0];
    expect(actionInfo.name).toBe('artifacts');
    // Mirrors `get-assets`, the sibling read action. Not type-enforced.
    expect(actionInfo.method).toBe('GET');
    expect(actionInfo.targetEntity?.toString()).toBe(PROC_TYPEID);
    expect(actionInfo.bodyParameters).toEqual({});
  });

  it('hydrates rows into Artifact instances on the property', async () => {
    callActionSpy.mockResolvedValue({ artifacts: [row('report.md'), row('plan.md')] } as never);
    const proc = new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING });

    const artifacts = await proc.loadArtifacts();

    expect(artifacts).toBe(proc.artifacts);
    expect(artifacts).toHaveLength(2);
    for (const a of artifacts) expect(a).toBeInstanceOf(Artifact);
    expect(artifacts.map((a) => a.name)).toEqual(['report.md', 'plan.md']);
    expect(artifacts[0].asset_ref).toBe('/repo/report.md');
  });

  it('reports every row as generated by this process', async () => {
    callActionSpy.mockResolvedValue({ artifacts: [row('report.md')] } as never);
    const proc = new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING });

    for (const a of await proc.loadArtifacts()) expect(a.generated_by).toBe(PROC_TYPEID);
  });

  it('yields [] when the key is absent, and when the response is empty', async () => {
    callActionSpy.mockResolvedValue({} as never);
    expect(await new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING }).loadArtifacts()).toEqual([]);

    callActionSpy.mockResolvedValue(undefined as never);
    expect(await new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING }).loadArtifacts()).toEqual([]);
  });

  it('does not latch "loaded" when the request rejects — a retry still fetches', async () => {
    const proc = new AgenticProcess({ id: PROC_ID, status: ProcessStatus.RUNNING });
    callActionSpy.mockRejectedValueOnce(new Error('backend down'));

    await expect(proc.loadArtifacts()).rejects.toThrow('backend down');
    expect(proc.artifacts).toEqual([]);

    callActionSpy.mockResolvedValue({ artifacts: [row('later.md')] } as never);
    await proc.loadArtifacts();

    expect(proc.artifacts.map((a) => a.name)).toEqual(['later.md']);
  });
});
