#!/usr/bin/env python3
"""make_style_shots.py — MAINTAINER-ONLY. Regenerate screenshots/<style>.png.

    uv run --with playwright python tools/make_style_shots.py [--style <slug>]

Playwright is NOT a Flowpad dependency (it is absent from pyproject.toml and
uv.lock) and end users have neither the package nor a browser. So style previews
are pre-generated by a maintainer and COMMITTED; they ship to users via the
`system_projects/**/*` package-data glob. Nothing at runtime needs this file —
`make_style_picker.py` only reads the committed PNGs and is stdlib-only.

Run this after adding or editing a style. It verifies as it goes:
  * zero console errors / failed requests per style, and
  * the display face actually RESOLVED (a style whose font silently fell back
    to system-ui is a broken style, and the screenshot would hide it).

For each style it builds the fixture deck, shoots the cover and the metrics
slide at 1280x720, and composes them 2-up into screenshots/<style>.png. The
cover sells the type and palette; the metrics slide is where design systems
actually diverge (a box, or a column under a rule?), so a cover alone would
flatter every style equally.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile

SKILL = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STYLES = os.path.join(SKILL, "styles")
SHOTS = os.path.join(SKILL, "screenshots")
TEMPLATE = os.path.join(SKILL, "template")
FIXTURE = os.path.join(SKILL, "tools", "fixture-deck.json")

# The two slides that go in the 2-up preview, named by layout so a fixture
# edit (reorder/insert) can't silently mis-shoot the wrong slide.
COVER_LAYOUT, METRICS_LAYOUT = "cover-centered", "metrics-grid"
SLIDE_W, SLIDE_H = 1280, 720
SHOT_W = 1280                  # composed 2-up width; each pane is SHOT_W/2
GAP = 8


def die(msg):
    sys.stderr.write("make_style_shots: error: %s\n" % msg)
    sys.exit(1)


def build_style_deck(slug, workdir):
    """Copy the scaffold, overlay the style, assemble the fixture deck."""
    dest = os.path.join(workdir, slug)
    shutil.copytree(TEMPLATE, dest)
    src = os.path.join(STYLES, slug)
    for f in ("tokens.css", "style.css"):
        shutil.copyfile(os.path.join(src, f), os.path.join(dest, "common", f))
    deck_path = os.path.join(dest, "deck.json")
    shutil.copyfile(FIXTURE, deck_path)
    out = os.path.join(workdir, slug + ".html")
    r = subprocess.run(
        [sys.executable, os.path.join(dest, "tools", "build_deck.py"),
         deck_path, "-o", out],
        capture_output=True, text=True)
    if r.returncode != 0:
        die("%s: build_deck failed: %s" % (slug, r.stderr.strip()))
    return out


def fixture_indices():
    """Map the two showcase layouts to their slide index in fixture-deck.json.

    Named lookup, not positional: a fixture reorder/insert then fails loudly
    here instead of silently shooting the wrong slide into the preview.
    """
    slides = json.load(open(FIXTURE, encoding="utf-8")).get("slides", [])
    idx = {}
    for i, slide in enumerate(slides):
        idx.setdefault(slide.get("layout"), i)
    out = []
    for layout in (COVER_LAYOUT, METRICS_LAYOUT):
        if layout not in idx:
            die("fixture-deck.json has no %r slide to preview" % layout)
        out.append(idx[layout])
    return out


def shoot(browser, slug, html, expect_face, indices):
    ctx = browser.new_context(viewport={"width": SLIDE_W, "height": SLIDE_H},
                             device_scale_factor=2)
    page = ctx.new_page()
    problems = []
    page.on("console", lambda m: problems.append("console: " + m.text)
            if m.type == "error" else None)
    page.on("pageerror", lambda e: problems.append("pageerror: " + str(e)))
    page.on("requestfailed", lambda r: problems.append("reqfail: " + r.url[:70]))

    page.goto("file://" + html, wait_until="load")
    page.wait_for_function(
        "() => typeof Reveal !== 'undefined' && Reveal.isReady && Reveal.isReady()",
        timeout=10_000)

    # Reveal's arrows/progress/slide-number are navigation chrome, not design.
    # They belong in a real deck but not in a style preview — a thumbnail should
    # show only what the style decides.
    page.add_style_tag(content=(
        ".reveal .controls, .reveal .progress, .reveal .slide-number "
        "{ display: none !important; }"))

    panes = []
    for idx in indices:
        page.evaluate("(n) => Reveal.slide(n, 0)", idx)
        page.wait_for_timeout(700)   # Reveal's fade fully settles
        panes.append(page.screenshot())

    face = page.evaluate(
        "() => { const h = document.querySelector('.reveal h1, .reveal h2');"
        " return h ? getComputedStyle(h).fontFamily.split(',')[0]"
        ".replace(/[\"']/g, '').trim() : ''; }")
    ctx.close()

    if problems:
        die("%s rendered with %d problem(s): %s"
            % (slug, len(problems), "; ".join(problems[:3])))
    if expect_face and face.lower() != expect_face.lower():
        die("%s: display face resolved to %r, expected %r — the font silently "
            "fell back and the style is broken" % (slug, face, expect_face))
    return panes, face


def compose(browser, panes, out_path):
    """Compose two slide PNGs side by side. Playwright only — no PIL."""
    pane_w = (SHOT_W - GAP) // 2
    pane_h = round(pane_w * SLIDE_H / SLIDE_W)
    imgs = "".join(
        '<img src="data:image/png;base64,%s" />'
        % base64.b64encode(p).decode("ascii") for p in panes)
    html = (
        "<!doctype html><meta charset='utf-8'><style>"
        "html,body{margin:0;padding:0;background:transparent}"
        ".s{display:flex;gap:%dpx;width:%dpx}"
        ".s img{width:%dpx;height:%dpx;display:block;object-fit:cover}"
        "</style><div class='s'>%s</div>" % (GAP, SHOT_W, pane_w, pane_h, imgs))
    ctx = browser.new_context(viewport={"width": SHOT_W, "height": pane_h},
                              device_scale_factor=1)
    page = ctx.new_page()
    page.set_content(html)
    page.wait_for_timeout(120)
    page.locator(".s").screenshot(path=out_path)
    ctx.close()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--style", help="only this slug (default: all)")
    args = ap.parse_args()

    try:
        from playwright.sync_api import sync_playwright
    except ModuleNotFoundError:
        die("playwright not installed. Run:\n"
            "    uv run --with playwright python -m playwright install chromium\n"
            "    uv run --with playwright python tools/make_style_shots.py")

    slugs = sorted(d for d in os.listdir(STYLES)
                   if os.path.isdir(os.path.join(STYLES, d)))
    if args.style:
        if args.style not in slugs:
            die("unknown style %r; have: %s" % (args.style, ", ".join(slugs)))
        slugs = [args.style]

    os.makedirs(SHOTS, exist_ok=True)
    indices = fixture_indices()
    total = 0
    # One Chromium for the whole run; per-style isolation comes from a fresh
    # context per screenshot, which is cheap. Relaunching per style (×2 phases)
    # would dominate the wall-clock.
    with tempfile.TemporaryDirectory() as work, sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True)
        try:
            for slug in slugs:
                meta = json.load(open(os.path.join(STYLES, slug, "style.json"),
                                      encoding="utf-8"))
                html = build_style_deck(slug, work)
                panes, face = shoot(browser, slug, html,
                                    meta.get("expect_face"), indices)
                out = os.path.join(SHOTS, slug + ".png")
                compose(browser, panes, out)
                kb = os.path.getsize(out) / 1024.0
                total += kb
                print("ok   %-16s %6.1f KB   face=%s" % (slug, kb, face))
        finally:
            browser.close()
    print("\n%d shot(s), %.0f KB total -> screenshots/" % (len(slugs), total))


if __name__ == "__main__":
    main()
